import './polyfills/custom'
// import './polyfills/url.min'
// import './polyfills/promise.min'
import './polyfills/fetch.iife'
import 'abortcontroller-polyfill/src/abortcontroller-polyfill'
import './polyfills/dom'
